---

    - name: Bacula7 Repository Get
      command: wget -P /etc/yum.repos.d/ https://copr.fedorainfracloud.org/coprs/slaanesh/Bacula/repo/epel-7/slaanesh-Bacula-epel-7.repo

    - name: Install Packages
      yum: name={{ item }} state=latest
      with_items:
        - bacula-director
        - bacula-client
        - bacula-storage
        - bacula-console
        - mariadb-server
        - MySQL-python
        - libselinux-python
        - wget

    - name: Start and Enable mysql
      service: name=mariadb state=started enabled=yes

    - name: Create Database for bacula
      mysql_db: name={{ dbname }} state=present

    - name: Create user for bacula
      mysql_user: name={{ dbuser }} password={{ dbpassword }} priv="bacula.*:ALL" host=localhost state=present

    - name: Create Bacula MySQL table
      command: /usr/libexec/bacula/make_bacula_tables mysql -u bacula --password={{ dbpassword }}

    - name: Director Default Storage Address Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='storage.example.com'
        replace='{{ ipaddress }}'
      with_items:
        - bacula-dir

    - name: Director Default Client Address Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='client.example.com'
        replace='{{ ipaddress }}'
      with_items:
        - bacula-dir

    - name: Director Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='dbpassword = ""'
        replace='dbpassword = "{{ dbpassword }}"'
      with_items:
        - bacula-dir

    - name: Director Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@DIR_PASSWORD@@'
        replace='bacula'
      with_items:
        - "{{ conf_name }}"
        - bconsole

    - name: SD Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@SD_PASSWORD@@'
        replace='bacula'
      with_items: conf_name

    - name: FD Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@FD_PASSWORD@@'
        replace='bacula'
      with_items: conf_name

    - name: MON DIR Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@MON_DIR_PASSWORD@@'
        replace='bacula'
      with_items: conf_name

    - name: MON SD Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@MON_SD_PASSWORD@@'
        replace='bacula'
      with_items: conf_name

    - name: MON FD Default Password Change
      replace:
        dest='/etc/bacula/{{ item }}.conf'
        regexp='@@MON_FD_PASSWORD@@'
        replace='bacula'
      with_items: conf_name

    - name: Start and Enable bacula
      service: name={{ item }} state=started enabled=yes
      with_items: conf_name

    - name: DB Command Change
      command: alternatives --set libbaccats.so /usr/lib64/libbaccats-mysql.so
